export interface MenuItem {
  id: string;
  name: string;
  nameEn?: string;
  description: string;
  descriptionEn?: string;
  price: number;
  category: string;
  ingredients: string[];
  removableIngredients?: string[];
  addableIngredients?: string[];
}

export const menuData: MenuItem[] = [
  // ANTIPASTI
  {
    id: "ant-1",
    name: "Insalata di polpo",
    description: "octopus, celery, pickled salad, lemon, garlic, pepper.",
    price: 16.0,
    category: "antipasti",
    ingredients: ["octopus", "celery", "pickled salad", "lemon", "garlic", "pepper"],
  },
  {
    id: "ant-2",
    name: "Cocktail di gamberi",
    description: "cocktail sauce, shrimp, julienned salad.",
    price: 16.0,
    category: "antipasti",
    ingredients: ["cocktail sauce", "shrimp", "julienned salad"],
  },
  {
    id: "ant-3",
    name: "Caponata di melanzana con cappuccetti",
    description: "Eggplant, celery, sugar, vinegar, onion, pepper, double concentrate, breaded croquettes.",
    price: 14.0,
    category: "antipasti",
    ingredients: ["eggplant", "celery", "sugar", "vinegar", "onion", "pepper", "double concentrate", "breaded croquettes"],
  },
  {
    id: "ant-4",
    name: "Gamberi in pastella (6 p)",
    description: "Shrimps, flour, beer, egg.",
    price: 14.0,
    category: "antipasti",
    ingredients: ["shrimps", "flour", "beer", "egg"],
  },
  {
    id: "ant-5",
    name: "Cozze scoppiate / zuppa",
    description: "Mussels, oil, garlic / Mussels, tomatoes, oil, chili, parsley.",
    price: 14.0,
    category: "antipasti",
    ingredients: ["mussels", "oil", "garlic", "tomatoes", "chili", "parsley"],
  },
  {
    id: "ant-6",
    name: "Cozze & gorgonzola",
    description: "Mussels, gorgonzola cheese.",
    price: 16.0,
    category: "antipasti",
    ingredients: ["mussels", "gorgonzola cheese"],
  },
  {
    id: "ant-7",
    name: "Polpo bollito",
    description: "Boiled Octopus.",
    price: 18.0,
    category: "antipasti",
    ingredients: ["octopus"],
  },
  {
    id: "ant-8",
    name: "Maialino con verdure fresche",
    description: "Cold-served oven-roasted suckling pig, infused with rosemary butter, accompanied by seasonal vegetables.",
    price: 16.0,
    category: "antipasti",
    ingredients: ["suckling pig", "rosemary butter", "seasonal vegetables"],
  },
  {
    id: "ant-9",
    name: "Caprese",
    description: "Tomatoes, mozzarella, oregano, salt, pepper, basil.",
    price: 8.0,
    category: "antipasti",
    ingredients: ["tomatoes", "mozzarella", "oregano", "salt", "pepper", "basil"],
  },
  {
    id: "ant-10",
    name: "Parmigiana di melanzana",
    description: "Eggplants, Parmesan cheese, onion, sugar, oil, salt, pepper, tomato sauce.",
    price: 8.0,
    category: "antipasti",
    ingredients: ["eggplants", "parmesan cheese", "onion", "sugar", "oil", "salt", "pepper", "tomato sauce"],
  },
  {
    id: "ant-11",
    name: "Bruschetta siciliana (2 pezzi con pomodoro + 2 pezzi con alici)",
    description: "Bread, tomato, anchovies, oil, garlic, basil, salt, pepper (4 p).",
    price: 6.0,
    category: "antipasti",
    ingredients: ["bread", "tomato", "anchovies", "oil", "garlic", "basil", "salt", "pepper"],
  },
  {
    id: "ant-12",
    name: "Misto caldo siciliano",
    description: "Panelle, crocchè, anelli di cipolla, patatine.",
    price: 10.0,
    category: "antipasti",
    ingredients: ["panelle", "crocchè", "onion rings", "fries"],
  },
  {
    id: "ant-13",
    name: "Polpette di pesce",
    description: "Fish, bread crumbs, cheese, pine nuts, raisins, basil, mint, salt, pepper, eggs.",
    price: 8.0,
    category: "antipasti",
    ingredients: ["fish", "bread crumbs", "cheese", "pine nuts", "raisins", "basil", "mint", "salt", "pepper", "eggs"],
  },
  
  // PRIMI
  {
    id: "pr-1",
    name: "Busiata gambero e pistacchio",
    description: "Busiata (pasta), prawns, extra virgin olive oil, white wine, garlic, pistachio, fish broth.",
    price: 20.0,
    category: "primi",
    ingredients: ["busiata pasta", "prawns", "extra virgin olive oil", "white wine", "garlic", "pistachio", "fish broth"],
  },
  {
    id: "pr-2",
    name: "Risotto / busiate ai profumi di mare",
    description: "Rice or pasta, mussels, clams, prawns, calamari, scampi, cherry tomatoes, chili pepper, garlic, parsley, fish broth.",
    price: 18.0,
    category: "primi",
    ingredients: ["rice or pasta", "mussels", "clams", "prawns", "calamari", "scampi", "cherry tomatoes", "chili pepper", "garlic", "parsley", "fish broth"],
  },
  {
    id: "pr-3",
    name: "Spaghetti & vongole",
    description: "Garlic, extra virgin olive oil, clams, parsley, black pepper.",
    price: 18.0,
    category: "primi",
    ingredients: ["garlic", "extra virgin olive oil", "clams", "parsley", "black pepper"],
  },
  {
    id: "pr-4",
    name: "Spaghetti ai ricci di mare",
    description: "Sea urchin, olive oil, pepper, parsley, chili pepper.",
    price: 28.0,
    category: "primi",
    ingredients: ["sea urchin", "olive oil", "pepper", "parsley", "chili pepper"],
  },
  {
    id: "pr-5",
    name: "Busiate, spada e melanzane",
    description: "Busiate (pasta), swordfish, garlic, mint, white wine, eggplant, chili pepper.",
    price: 18.0,
    category: "primi",
    ingredients: ["busiate pasta", "swordfish", "garlic", "mint", "white wine", "eggplant", "chili pepper"],
  },
  {
    id: "pr-6",
    name: "Cous cous di pesce",
    description: "Couscous semolina, mussels, clams, prawns, calamari, scampi, white fish, cherry tomatoes, chili pepper, garlic, parsley, fish broth.",
    price: 22.0,
    category: "primi",
    ingredients: ["couscous semolina", "mussels", "clams", "prawns", "calamari", "scampi", "white fish", "cherry tomatoes", "chili pepper", "garlic", "parsley", "fish broth"],
  },
  {
    id: "pr-7",
    name: "Busiate alla norma",
    description: "Busiate (pasta), tomato sauce, salted ricotta, eggplant, onion, basil.",
    price: 14.0,
    category: "primi",
    ingredients: ["busiate pasta", "tomato sauce", "salted ricotta", "eggplant", "onion", "basil"],
  },
  {
    id: "pr-8",
    name: "Busiate con pesto alla trapanese",
    description: "Busiate (pasta), garlic, almonds, pecorino cheese, basil, tomato, pepper.",
    price: 12.0,
    category: "primi",
    ingredients: ["busiate pasta", "garlic", "almonds", "pecorino cheese", "basil", "tomato", "pepper"],
  },
  {
    id: "pr-9",
    name: "Spaghetti alla carbonara",
    description: "Eggs, pork cheek (guanciale), pecorino cheese, parmesan cheese, black pepper.",
    price: 12.0,
    category: "primi",
    ingredients: ["eggs", "pork cheek (guanciale)", "pecorino cheese", "parmesan cheese", "black pepper"],
  },
  {
    id: "pr-10",
    name: "Gnocchi, gorgonzola e noci",
    description: "Potato gnocchi, gorgonzola cheese, walnuts.",
    price: 14.0,
    category: "primi",
    ingredients: ["potato gnocchi", "gorgonzola cheese", "walnuts"],
  },
  
  // SECONDI
  {
    id: "sec-1",
    name: "Frittura di calamari",
    description: "Calamari, flour",
    price: 16.0,
    category: "secondi",
    ingredients: ["calamari", "flour"],
  },
  {
    id: "sec-2",
    name: "Pesce spada ai ferri",
    description: "Swordfish, oil, salt",
    price: 14.0,
    category: "secondi",
    ingredients: ["swordfish", "oil", "salt"],
  },
  {
    id: "sec-3",
    name: "Tagliata di tonno al pistacchio / sesamo",
    description: "Tuna fish, pistachio / sesame, oil",
    price: 18.0,
    category: "secondi",
    ingredients: ["tuna fish", "pistachio", "sesame", "oil"],
  },
  {
    id: "sec-4",
    name: "Tagliata di tonno al naturale",
    description: "Tuna fish, oil",
    price: 16.0,
    category: "secondi",
    ingredients: ["tuna fish", "oil"],
  },
  {
    id: "sec-5",
    name: "Calamaro alla griglia",
    description: "Calamari, oil",
    price: 18.0,
    category: "secondi",
    ingredients: ["calamari", "oil"],
  },
  {
    id: "sec-6",
    name: "Pescato del giorno",
    description: "Catch of the day",
    price: 60.0,
    category: "secondi",
    ingredients: ["catch of the day"],
  },
  {
    id: "sec-7",
    name: "Pesce spada all'eoliana",
    description: "capers, onion, cherry tomatoes, swordfish, olives, fish broth, parsley",
    price: 18.0,
    category: "secondi",
    ingredients: ["capers", "onion", "cherry tomatoes", "swordfish", "olives", "fish broth", "parsley"],
  },
  {
    id: "sec-8",
    name: "Filetto al gorgonzola",
    description: "Beef fillet with gorgonzola",
    price: 18.0,
    category: "secondi",
    ingredients: ["beef fillet", "gorgonzola"],
  },
  {
    id: "sec-9",
    name: "Filetto ai funghi porcini",
    description: "Beef fillet with porcini mushrooms",
    price: 18.0,
    category: "secondi",
    ingredients: ["beef fillet", "porcini mushrooms"],
  },
  {
    id: "sec-10",
    name: "Filetto ai ferri",
    description: "Grilled beef fillet",
    price: 18.0,
    category: "secondi",
    ingredients: ["beef fillet"],
  },
  {
    id: "sec-11",
    name: "Tagliata di scottona con rucola, grana e pomodorini",
    description: "Sliced beef sirloin with arugula, parmesan, and cherry tomatoes",
    price: 20.0,
    category: "secondi",
    ingredients: ["beef sirloin", "arugula", "parmesan", "cherry tomatoes"],
  },
  
  // CONTORNI
  {
    id: "cont-1",
    name: "Verdure grigliate",
    description: "Grilled vegetables",
    price: 7.0,
    category: "contorni",
    ingredients: ["grilled vegetables"],
  },
  {
    id: "cont-2",
    name: "Insalata mista",
    description: "Mixed salad",
    price: 6.0,
    category: "contorni",
    ingredients: ["mixed salad"],
  },
  {
    id: "cont-3",
    name: "Insalata siciliana",
    description: "Sicilian salad",
    price: 6.0,
    category: "contorni",
    ingredients: ["sicilian salad"],
  },
  {
    id: "cont-4",
    name: "Patate al forno",
    description: "Baked potatoes",
    price: 7.0,
    category: "contorni",
    ingredients: ["baked potatoes"],
  },
  
  // PIZZE
  {
    id: "piz-1",
    name: "LA BIANCA NEVE",
    description: "Mozzarella fior di latte / Mozzarella and olive oil",
    price: 6.0,
    category: "pizze",
    ingredients: ["mozzarella fior di latte", "olive oil"],
  },
  {
    id: "piz-2",
    name: "MARGHERITA",
    description: "Pomodoro, mozzarella, basilico / Tomato, mozzarella, basil and olive oil",
    price: 7.0,
    category: "pizze",
    ingredients: ["tomato", "mozzarella", "basil", "olive oil"],
  },
  {
    id: "piz-3",
    name: "MARINARA",
    description: "Pomodoro, aglio, origano e acciughe / Tomato, garlic, oregano and anchovies",
    price: 7.0,
    category: "pizze",
    ingredients: ["tomato", "garlic", "oregano", "anchovies"],
  },
  {
    id: "piz-4",
    name: "NAPOLI",
    description: "Pomodoro, mozzarella, acciughe, origano / Tomato sauce, mozzarella, anchovies and oregano",
    price: 8.0,
    category: "pizze",
    ingredients: ["tomato sauce", "mozzarella", "anchovies", "oregano"],
  },
  {
    id: "piz-5",
    name: "DIAVOLA",
    description: "Pomodoro, mozzarella, salame piccante / Tomato, mozzarella, spicy salami",
    price: 9.0,
    category: "pizze",
    ingredients: ["tomato", "mozzarella", "spicy salami"],
  },
  {
    id: "piz-6",
    name: "ROMANA",
    description: "Pomodoro, mozzarella, prosciutto cotto / Tomato, mozzarella, ham, olive oil",
    price: 9.0,
    category: "pizze",
    ingredients: ["tomato", "mozzarella", "ham", "olive oil"],
  },
  {
    id: "piz-7",
    name: "CAPRICCIOSA",
    description: "Pomodoro, mozzarella, prosciutto cotto, funghi, carciofi, olive, würstel / Tomato, mozzarella, ham, mushrooms, artichokes, olives, frankfurters",
    price: 10.0,
    category: "pizze",
    ingredients: ["tomato", "mozzarella", "ham", "mushrooms", "artichokes", "olives", "frankfurters"],
  },
  {
    id: "piz-8",
    name: "RUCOLIANA",
    description: "Pomodoro, mozzarella, prosciutto crudo, rucola e scaglie di grana /Tomato, mozzarella, cooked ham, rocket and flakes",
    price: 11.0,
    category: "pizze",
    ingredients: ["tomato", "mozzarella", "prosciutto crudo", "arugula", "parmesan flakes"],
  },
  {
    id: "piz-9",
    name: "ORIGANATA",
    description: "Pomodoro, cipolla, cacio cavallo, acciughe, parmigiano, origano / Tomato base with onion, caciocavallo cheese, anchovies, parmesan and oregano",
    price: 9.0,
    category: "pizze",
    ingredients: ["tomato", "onion", "caciocavallo cheese", "anchovies", "parmesan", "oregano"],
  },
  {
    id: "piz-10",
    name: "CALZONE",
    description: "Pomodoro, mozzarella, prosciutto cotto / Tomato, mozzarella, ham, olive oil",
    price: 10.0,
    category: "pizze",
    ingredients: ["tomato", "mozzarella", "ham", "olive oil"],
  },
  {
    id: "piz-11",
    name: "4 FORMAGGI",
    description: "Mozzarella, gorgonzola, emmenthal, parmigiano / Mozzarella, gorgonzola, emmenthal, Parmigiano cheese, olive oil",
    price: 10.0,
    category: "pizze",
    ingredients: ["mozzarella", "gorgonzola", "emmenthal", "parmesan", "olive oil"],
  },
  {
    id: "piz-12",
    name: "VEGETARIANA",
    description: "Mozzarella, friarielli, melanzane, carciofi, funghi, pomodorini / Mozzarella, vegetables, aubergine, artichokes, mushrooms, cherry tomatoes, olive oil",
    price: 9.0,
    category: "pizze",
    ingredients: ["mozzarella", "friarielli", "eggplant", "artichokes", "mushrooms", "cherry tomatoes", "olive oil"],
  },
  {
    id: "piz-13",
    name: "TONNO E CIPOLLA",
    description: "Mozzarella, tonno, cipolla, olive / Mozzarella, tuna, onion, olives, oil",
    price: 9.0,
    category: "pizze",
    ingredients: ["mozzarella", "tuna", "onion", "olives", "oil"],
  },
  {
    id: "piz-14",
    name: "PATATOSA",
    description: "Mozzarella, pomodoro, patatine fritte / Mozzarella, tomato, french fries",
    price: 9.0,
    category: "pizze",
    ingredients: ["mozzarella", "tomato", "french fries"],
  },
  {
    id: "piz-15",
    name: "4 GUSTI",
    description: "Prosciutto cotto, funghi, carciofi, olive nere / Cooked ham, mushrooms, artichoke hearts, black olives",
    price: 10.0,
    category: "pizze",
    ingredients: ["cooked ham", "mushrooms", "artichoke hearts", "black olives"],
  },
  {
    id: "piz-16",
    name: "PROSCIUTTO & FUNGHI",
    description: "Cooked ham, mushrooms",
    price: 9.0,
    category: "pizze",
    ingredients: ["cooked ham", "mushrooms"],
  },
  {
    id: "piz-17",
    name: "LA BUFALA",
    description: "Pomodoro, mozzarella di bufala, basilico / Tomato sauce, buffalo mozzarella and fresh basil",
    price: 10.0,
    category: "pizze",
    ingredients: ["tomato sauce", "buffalo mozzarella", "fresh basil"],
  },
  {
    id: "piz-18",
    name: "PARMIGIANA",
    description: "Pomodoro, mozzarella, melanzane fritte, parmigiano, basilico / Tomato, mozzarella, fried aubergines, parmigiano cheese, basil and olive oil",
    price: 10.0,
    category: "pizze",
    ingredients: ["tomato", "mozzarella", "fried eggplant", "parmesan", "basil", "olive oil"],
  },
  {
    id: "piz-19",
    name: "VERONIKA",
    description: "Pizza base con mozzarella di bufala, prosciutto crudo, rucola, pomodorini, scaglie di grana / Pizza bread, buffalo mozzarella, raw ham, rocket, cherry tomatoes, grana cheese flakes and olive oil",
    price: 14.0,
    category: "pizze",
    ingredients: ["buffalo mozzarella", "prosciutto crudo", "arugula", "cherry tomatoes", "grana cheese flakes", "olive oil"],
  },
  {
    id: "piz-20",
    name: "MORTAZZA",
    description: "Bianca neve con mortadella, granella di pistacchio, mozzarella di bufala / White pizza with mortadella, chopped pistachios, olive oil",
    price: 13.0,
    category: "pizze",
    ingredients: ["mortadella", "chopped pistachios", "buffalo mozzarella", "olive oil"],
  },
  {
    id: "piz-21",
    name: "SALSICCIA & FRIARIELLI",
    description: "mozzarella di bufala, salsiccia, friarielli, olio / Buffalo mozzarella, Italian sausage, broccoli rabe and a drizzle of olive oil",
    price: 12.0,
    category: "pizze",
    ingredients: ["buffalo mozzarella", "italian sausage", "broccoli rabe", "olive oil"],
  },
  {
    id: "piz-22",
    name: "KATIA",
    description: "mozzarella di bufala, pancetta, patate al forno aromatizzate, provola affumicata, olio / Buffalo mozzarella, bacon, flavored baked potatoes, smoked provola, extra virgin olive oil",
    price: 12.0,
    category: "pizze",
    ingredients: ["buffalo mozzarella", "bacon", "flavored baked potatoes", "smoked provola", "extra virgin olive oil"],
  },
  {
    id: "piz-23",
    name: "GUSTOSA",
    description: "mozzarella di bufala, pancetta, funghi porcini, scaglie di grana / Buffalo mozzarella, bacon, porcini mushrooms, grana cheese flakes, olive oil",
    price: 12.0,
    category: "pizze",
    ingredients: ["buffalo mozzarella", "bacon", "porcini mushrooms", "grana cheese flakes", "olive oil"],
  },
  {
    id: "piz-24",
    name: "ESTATE",
    description: "mozzarella di bufala, zucchine fritte, menta, parmigiano / Buffalo mozzarella, fried zucchini, mint, parmesan",
    price: 10.0,
    category: "pizze",
    ingredients: ["buffalo mozzarella", "fried zucchini", "mint", "parmesan"],
  },
  {
    id: "piz-25",
    name: "SALMONE",
    description: "Pizza bianca, mozzarella fior di latte, salmone affumicato, olio, limone / White pizza topped with mozzarella, smoked salmon, a drizzle of olive oil and lemon juice",
    price: 12.0,
    category: "pizze",
    ingredients: ["mozzarella fior di latte", "smoked salmon", "olive oil", "lemon juice"],
  },
  {
    id: "piz-26",
    name: "CARBONARA",
    description: "Mozzarella, carbocrema, guanciale croccante, pepe, parmigiano / Mozzarella, carbonara cream, crispy bacon, pepper, parmesan cheese",
    price: 10.0,
    category: "pizze",
    ingredients: ["mozzarella", "carbonara cream", "crispy bacon", "pepper", "parmesan cheese"],
  },
  {
    id: "piz-27",
    name: "GUANCIALOTTA",
    description: "Mozzarella, pomodoro, guanciale, parmigiano / Mozzarella, tomato, bacon, parmesan cheese",
    price: 9.0,
    category: "pizze",
    ingredients: ["mozzarella", "tomato", "bacon", "parmesan cheese"],
  },
  {
    id: "piz-28",
    name: "TARTUFATA",
    description: "bufala affumicata, funghi porcini, speck, olio di tartufo / Smoked buffalo, porcini mushrooms, speck, truffle oil",
    price: 14.0,
    category: "pizze",
    ingredients: ["smoked buffalo", "porcini mushrooms", "speck", "truffle oil"],
  },
  {
    id: "piz-29",
    name: "BELEN",
    description: "pomodoro, mozzarella, salame piccante, salsiccia, patate al forno, glassa aceto balsamico / Tomato, mozzarella, spicy salami, sausage, baked potatoes, balsamic vinegar glaze",
    price: 11.0,
    category: "pizze",
    ingredients: ["tomato", "mozzarella", "spicy salami", "sausage", "baked potatoes", "balsamic vinegar glaze"],
  },
  {
    id: "piz-30",
    name: "LE GRAZIE",
    description: "Pomodoro, mozzarella, salame paisanella, scamorza, gorgonzola / Tomato, mozzarella, salame paisanella, scamorza cheese, gorgonzola cheese",
    price: 13.0,
    category: "pizze",
    ingredients: ["tomato", "mozzarella", "salame paisanella", "scamorza cheese", "gorgonzola cheese"],
  },
  {
    id: "piz-31",
    name: "MESSICANA",
    description: "Pomodoro, mozzarella, salsiccia, salame piccante, gorgonzola, tabasco / Tomato, mozzarella, sausage, spicy salami, gorgonzola cheese, tabasco",
    price: 13.0,
    category: "pizze",
    ingredients: ["tomato", "mozzarella", "sausage", "spicy salami", "gorgonzola cheese", "tabasco"],
  },
  {
    id: "piz-32",
    name: "PAISANELLA",
    description: "Mozzarella, salame Paisanella, scamorza, pistacchio / Mozzarella, salame Paisanella, scamorza cheese, pistachio",
    price: 13.0,
    category: "pizze",
    ingredients: ["mozzarella", "salame paisanella", "scamorza cheese", "pistachio"],
  },
  {
    id: "piz-33",
    name: "TRIFOLATA",
    description: "Pomodoro, mozzarella, funghi trifolati, scamorza, speck / Tomato, mozzarella, sliced mushrooms, scamorza cheese, speck",
    price: 15.0,
    category: "pizze",
    ingredients: ["tomato", "mozzarella", "sliced mushrooms", "scamorza cheese", "speck"],
  },
  {
    id: "piz-34",
    name: "ITALIANA",
    description: "Pizza pane, pomodoro, pomodorino, mozzarella di bufala, olive, olio, origano (tutto a crudo) / Pizza bread, tomato, cherry tomato, buffalo mozzarella, olives, oil, oregano (all raw)",
    price: 13.0,
    category: "pizze",
    ingredients: ["tomato", "cherry tomato", "buffalo mozzarella", "olives", "oil", "oregano"],
  },
  
  // BEVANDE
  {
    id: "bev-1",
    name: "Acqua",
    description: "naturale / frizzante/ Ferrarelle 0,75 l",
    price: 3.0,
    category: "bevande",
    ingredients: ["water"],
  },
  {
    id: "bev-2",
    name: "Acqua",
    description: "0,50 l",
    price: 2.5,
    category: "bevande",
    ingredients: ["water"],
  },
  {
    id: "bev-3",
    name: "Coca Cola",
    description: "1 L",
    price: 6.0,
    category: "bevande",
    ingredients: ["coca cola"],
  },
  {
    id: "bev-4",
    name: "Coca Cola, Coca Cola Zero, Fanta",
    description: "0,33 l",
    price: 3.0,
    category: "bevande",
    ingredients: ["soft drink"],
  },
  {
    id: "bev-5",
    name: "Succo di frutta",
    description: "pesca, pera, mirtillo & mela",
    price: 3.0,
    category: "bevande",
    ingredients: ["fruit juice"],
  },
  {
    id: "bev-6",
    name: "Limonata Polara",
    description: "0,275 L",
    price: 4.0,
    category: "bevande",
    ingredients: ["lemonade"],
  },
  {
    id: "bev-7",
    name: "Estathè",
    description: "pesca / limone 0,40 L",
    price: 3.5,
    category: "bevande",
    ingredients: ["iced tea"],
  },
  {
    id: "bev-8",
    name: "Spremuta d'arancia",
    description: "",
    price: 4.0,
    category: "bevande",
    ingredients: ["orange juice"],
  },
  
  // BIRRE
  {
    id: "bir-1",
    name: "Bionda",
    description: "alla spina / draft 0,5 l",
    price: 6.0,
    category: "birre",
    ingredients: ["beer"],
  },
  {
    id: "bir-2",
    name: "Bionda",
    description: "alla spina / draft 0,3 l",
    price: 4.0,
    category: "birre",
    ingredients: ["beer"],
  },
  {
    id: "bir-3",
    name: "Rossa",
    description: "alla spina / draft 0,5 l",
    price: 8.0,
    category: "birre",
    ingredients: ["beer"],
  },
  {
    id: "bir-4",
    name: "Beck's",
    description: "0,33 l",
    price: 3.5,
    category: "birre",
    ingredients: ["beer"],
  },
  {
    id: "bir-5",
    name: "Rossa",
    description: "alla spina / draft 0,3 l",
    price: 6.0,
    category: "birre",
    ingredients: ["beer"],
  },
  {
    id: "bir-6",
    name: "Heineken",
    description: "0,33 l",
    price: 3.0,
    category: "birre",
    ingredients: ["beer"],
  },
  {
    id: "bir-7",
    name: "Ceres",
    description: "0,33 l",
    price: 4.5,
    category: "birre",
    ingredients: ["beer"],
  },
  {
    id: "bir-8",
    name: "Messina",
    description: "0,33 l",
    price: 4.0,
    category: "birre",
    ingredients: ["beer"],
  },
  {
    id: "bir-9",
    name: "Corona",
    description: "0,33 l",
    price: 3.0,
    category: "birre",
    ingredients: ["beer"],
  },
  {
    id: "bir-10",
    name: "Peroni limone",
    description: "0,33 l",
    price: 3.0,
    category: "birre",
    ingredients: ["beer"],
  },
  {
    id: "bir-11",
    name: "Analcolica",
    description: "0,33 l",
    price: 3.0,
    category: "birre",
    ingredients: ["beer"],
  },
  {
    id: "bir-12",
    name: "Senza glutine",
    description: "0,33 l",
    price: 3.0,
    category: "birre",
    ingredients: ["beer"],
  },
  
  // CAFFETTERIA
  {
    id: "caf-1",
    name: "Caffè",
    description: "",
    price: 1.5,
    category: "caffetteria",
    ingredients: ["coffee"],
  },
  {
    id: "caf-2",
    name: "Cappuccino",
    description: "",
    price: 3.0,
    category: "caffetteria",
    ingredients: ["coffee", "milk", "foam"],
  },
  {
    id: "caf-3",
    name: "Shakerato",
    description: "",
    price: 5.0,
    category: "caffetteria",
    ingredients: ["coffee", "ice"],
  },
  {
    id: "caf-4",
    name: "Caffellatte",
    description: "",
    price: 3.0,
    category: "caffetteria",
    ingredients: ["coffee", "milk"],
  },
  {
    id: "caf-5",
    name: "Latte macchiato",
    description: "",
    price: 3.0,
    category: "caffetteria",
    ingredients: ["coffee", "milk"],
  },
];

export const menuCategories = [
  { id: "antipasti", name: "Antipasti / Appetizers", nameEn: "Appetizers" },
  { id: "primi", name: "I primi / First courses", nameEn: "First courses" },
  { id: "secondi", name: "Secondi / Main courses", nameEn: "Main courses" },
  { id: "contorni", name: "Contorni / Side dishes", nameEn: "Side dishes" },
  { id: "pizze", name: "Pizze", nameEn: "Pizzas" },
  { id: "bevande", name: "Bevande / Drinks", nameEn: "Drinks" },
  { id: "birre", name: "Birre / Beers", nameEn: "Beers" },
  { id: "caffetteria", name: "Caffè", nameEn: "Coffee" },
];

